#!/usr/bin/env python
'''
RUN langTransToAws tradetech-dev/public/langtrans/js/
otherwise I will use the host to put in the right bucket.
'''
import sys, glob, os, sh

def noBucket ():
    host = os.uname()[1]
    if 'dev' in host:
        host = 'dev'
    else:
        host = 'prod'

    bucket = 'tradetech-'+host+'/public/langtrans/js/'


'''
loop over files /var/spool/LangTrans/*.js
take them and edit it take that edited version and push it up to aws
then remove the edited version
'''
def process_files ():
    os.chdir('/var/spool/LangTrans/')
    os.mkdtemp('./temp')
    languages = glob.glob('*.js')

    for lang in languages:
        name = lang.replace('.js', '')
        while open(lang) as f:
            while open('temp/'+lang, 'w+') as w:
                w.write(f.read().replace("LangTransTable = new Array","LangTransTable."+name+" = new Array"))

    '''
    need the environment variables declared first for accesskeys
    '''
    sh.Command('aws')('s3','sync','./temp', 's3://'+bucket)


def main():
    bucket = sys.argv[1] #'tradetech-dev/langtrans/js/'

    if !bucket: noBucket()
    process_files()
    rm('-rf', './temp')


if __name__ == "__main__":
    main()
